package localizable

const SPANISH = "es"

const ES = `
"appName" = "godcr";
"appTitle" = "godcr (%s)";
"recentTransactions" = "Transacciones Recientes";
"recentProposals" = "Propuestas Recientes";
"seeAll" = "Ver todo";
"send" = "Enviar";
"receive" = "Recibir";
"online" = "En línea";
"offline" = "Desconectado";
"showDetails" = "Mostrar detalles";
"hideDetails" = "Ocultar detalles";
"peers" = "Compañeros";
"connectedPeersCount" = "Número de nodos conectados";
"noConnectedPeer" = "No hay nodos conectados.";
"disconnect" = "Desconectar";
"reconnect" = "Volver a conectar";
"currentTotalBalance" = "Saldo total actual";
"totalBalance" = "Saldo total";
"walletStatus" = "Estado de la cartera";
"blockHeaderFetched" = "Encabezados de bloque obtenidos";
"noTransactions" = "No hay transacciones.";
"fetchingBlockHeaders" = "Obteniendo encabezados de bloque · %v%%";
"discoveringWalletAddress" = "Descubriendo la dirección de la billetera · %v%%";
"rescanningHeaders" = "Volver a escanear encabezados · %v%%";
"rescanningBlocks" = "Volver a escanear bloques";
"blocksScanned" = "Bloques escaneados";
"blocksLeft" = "%d quedan bloques";
"autoSync" = "Sincronización automática";
"syncSteps" = "Paso %d/3";
"blockHeaderFetchedCount" = "%d de %d";
"timeLeft" = "%v restante";
"connectedTo" = "Conectado a";
"connecting" = "Conectando...";
"synced" = "Sincronizado";
"syncingState" = "Sincronizando...";
"waitingState" = "Esperando...";
"walletNotSynced" = "No sincronizado";
"rebroadcast" = "Retransmitir";
"cancel" = "Cancelar";
"resumeAccountDiscoveryTitle" = "Desbloquear para reanudar la restauración";
"unlock" = "Desbloquear";
"syncingProgress" = "Progreso de la sincronización";
"syncingProgressStat" = "%s detrás";
"noWalletLoaded" = "Sin cartera cargada";
"lastBlockHeight" = "Altura del último bloque";
"ago" = "atrás";
"newest" = "Recientes";
"oldest" = "Antiguas";
"all" = "Todas";
"transferred" = "Transferida";
"sent" = "Enviadas";
"received" = "Recibidas";
"yourself" = "A la misma cuenta";
"mixed" = "Mixte";
"unmined" = "sin minar";
"immature" = "Inmaduro";
"voted" = "Votado";
"revoked" = "Revocado";
"live" = "Vivir";
"expired" = "Caducado";
"purchased" = "Comprado";
"revocation" ="Revocación";
"staking" = "replanteo";
"immatureRewards" = "Recompensas inmaduras";
"lockedByTickets" = "Bloqueado por boletos";
"immatureStakeGen" = "Generación de estaca inmadura";
"votingAuthority" = "Autoridad de votación";
"unknown" = "Desconocido";
"nConfirmations" = "%d Confirmaciones";
"from" = "De";
"to" = "Enviar a";
"fee" = "Tarifa";
"includedInBlock" = "Incluido en bloque";
"type" = "Type";
"transactionId" = "ID de la transacción";
"xInputsConsumed" = "%d Entradas consumidas";
"xOutputCreated" = "%d Salidas creadas";
"viewOnDcrdata" = "Ver en dcrdata";
"watchOnlyWallets" = "Carteras de solo mirar";
"signMessage" = "Firmar mensaje";
"verifyMessage" = "Verificar mensaje";
"message" = "Mensaje";
"viewProperty" = "Ver propiedad";
"stakeShuffle" = "StakeShuffle";
"rename" = "Renombrar";
"renameWalletSheetTitle" = "Renombrar la cartera";
"settings" = "Configuración";
"createANewWallet" = "Crear una nueva cartera"
"importExistingWallet" = "Importar una cartera existente";
"importWatchingOnlyWallet" = "Importar una cartera de solo mirar";
"create" = "Crear";
"watchOnlyWalletImported" = "Cartera de solo mirar importada";
"addNewAccount" = "Agregar una nueva cuenta";
"notBackedUp" = "Cuenta no respaldada";
"labelSpendable" = "Disponible";
"backupSeedPhrase" = "Copia de seguridad de las palabras semilla";
"verifySeedInfo" = "Verifique la copia de seguridad de sus palabras semilla para que pueda recuperar sus fondos cuando sea necesario.";
"createNewAccount" = "Crear una nueva cuenta";
"invalidPassphrase" = "La contraseña ingresada no es válida.";
"Import" = "Importar";
"spendingPasswordInfo" = "Una contraseña de gastos ayuda a proteger las transacciones de su billetera."
"spendingPassword" = "Contraseña de gasto";
"changeSpendingPass" = "Cambiar la contraseña de gasto";
"currentSpendingPassword" = "Contraseña de gasto actual";
"newSpendingPassword" = "Nueva contraseña de gastos";
"confirmNewSpendingPassword" = "Confirmer le nouveau mot de passe de dépenses";
"spendingPasswordUpdated" = "Contraseña de gastos actualizada";
"notifications" = "Notificaciones";
"beepForNewBlocks" = "Beep (notificación) para los nuevos bloques";
"debug" = "Depurar";
"rescanBlockchain" = "Volver a escanear la blockchain";
"dangerZone" = "Zona peligrosa";
"removeWallet" = "Eliminar la cartera del dispositivo";
"change" = "Cambiar";
"notConnected" = "No conectado a la red de decred";
"rescanProgressNotification" = "Verifique el progreso en el resumen de la cuenta.";
"rescanInfo" = "Volver a escanear puede ayudar a resolver algunos errores de saldo. Esto llevará algún tiempo, ya que escanea toda la cadena de bloques en busca de transacciones."
"rescan" = "Volver a escanear";
"confirmToRemove" = "Confirmar para eliminar";
"remove" = "Eliminar";
"confirm" = "Confirmar";
"general" = "General";
"unconfirmedFunds" = "Gastar fondos no confirmados";
"confirmed" = "Confirmado";
"currencyConversion" = "Conversión de Moneda";
"language" = "Idioma";
"security" = "Seguridad";
"startupPassword" = "Contraseña de inicio";
"changeStartupPassword" = "Cambiar la contraseña de inicio";
"connection" = "Conexión";
"connectToSpecificPeer" = "Conectarse a un nodo específico";
"changeSpecificPeer" = "Cambiar un nodo en específico";
"CustomUserAgent" = "Agente de usuario personalizado";
"userAgentSummary" = "Para obtener el tipo de cambio";
"changeUserAgent" = "Cambiar el agente de usuario";
"createStartupPassword" = "Crea una contraseña de inicio";
"confirmRemoveStartupPass" = "Confirmar para desactivar la contraseña de inicio";
"userAgentDialogTitle" = "Configurar el agente de usuario";
"overview" = "Resumen";
"transactions" = "Transacciones";
"wallets" = "Carteras";
"tickets" = "Tickets";
"more" = "Más Opciones";
"english" = "Inglés";
"french" = "Francés";
"spanish" = "Español";
"usdBittrex" = "USD (Bittrex)";
"none" = "Ninguno";
"proposals" = "Propuestas";
"governance" = "Gobernancia";
"staking" = "replanteo";
"pending" = "Pendiente";
"vote" = "Votar";
"revoke" = "Revocar";
"maturity" = "Madurez";
"yesterday" = "el dia de ayer";
"days" = "dias";
"hours" = "Horas";
"mins" = "minutos";
"secs" = "segundos";
"weekAgo" = "%d semana ago";
"weeksAgo" = "%d semanas ago";
"yearAgo" = "%d año ago";
"yearsAgo" = "%d años ago";  
"monthAgo" = "%d mes ago";
"monthsAgo" = "%d meses ago";
"dayAgo" = "%d día ago";
"daysAgo" = "%d dias ago";
"hourAgo" = "%d hora ago";
"hoursAgo" = "%d horas ago";
"minuteAgo" = "%d minuto ago";
"minutesAgo" = "%d minutos ago";
"justNow" = "Justo ahora";
"imawareOfRisk" = "soy consciente del riesgo";
"unmixedBalance" = "Saldo sin mezclar";
"backupLater" = "Copia de seguridad más tarde";
"backupNow" = "Copia ahora";
"status" = "Estado";
"daysToVote" = "Días para votar";
"reward" = "Premio";
"viewTicket" = "Ver ticket asociado";
"external" = "Externo";
"republished" = "Transacciones no minadas republicadas en la red decretada";
"copied" = "Copiado";
"txHashCopied" = "Hash de transacción copiado"";
"addressCopied" = "Dirección copiada";
"address" = "Dirección";
"acctDetailsKey" = "%d externo, %d interno, %d importado";
"key" = "Llave"
"acctNum" = "Número de cuenta";
"acctName" = "Nombre de la cuenta";
"acctRenamed" = "Cuenta renombrada";
"acctCreated" = "Cuenta creada"
"renameAcct" = "Vuelva a nombrar la cuenta";
"hdPath" = "Ruta HD";
"validateWalSeed" = "Validar semillas de billetera";
"clearAll" = "Limpiar todo";
"restoreWallet" = "Restaurar billetera";
"enterSeedPhrase" = "Ingrese su frase inicial";
"invalidSeedPhrase" = "Frase inicial no válida"
"seedAlreadyExist" = "Ya existe una billetera con una semilla idéntica."
"walletRestored" = "Monedero restaurado"
"enterWalletDetails" = "Ingrese los detalles de la billetera"
"copy" = "Dupdo"
"enterAddressToSign" = "Introduce una dirección y un mensaje para firmar:"
"signCopied" = "Firma copiada"
"signature" = "Firma"
"confirmToSign" = "Confirmar para firmar"
"enterValidAddress" = "Por favor introduce una dirección válida"
"enterValidMsg" = "Por favor ingrese un mensaje válido para firmar"
"invalidAddress" = "Dirección inválida"
"addrNotOwned" = "Dirección que no pertenece a ningún monedero"
"delete" = "Borrar"
"walletName" = "Nombre de la billetera"
"walletRenamed" = "Monedero renombrado"
"walletCreated" = "Monedero creado"
"addWallet" = "Agregar billetera"
"checkMixerStatus" = "Comprobar el estado del mezclador"
"walletRestoreMsg" = "Puede restaurar esta billetera desde la palabra inicial después de que se elimine."
"walletRemoved" = "Monedero eliminado"
"walletRemoveInfo" = "Asegúrese de tener una copia de seguridad de la palabra semilla antes de quitar la billetera"
"watchOnlyWalletRemoveInfo" = "La billetera de solo reloj se eliminará de su aplicación"
"gotIt" = "Entiendo"
"noValidAccountFound" = "no se encontró una cuenta válida"
"mixer" = "Mezclador"
"readyToMix" = "Listo para mezclar"
"mixerRunning" = "El mezclador está funcionando..."
"keepAppOpen" = "Mantener esta aplicación abierta"
"mixerShutdown" = "La mezcladora se detendrá automáticamente cuando el resto sin mezclar esté completamente mezclado."
"votingPreference" = "Preferencia de voto:"
"noAgendaYet" = "No hay agendas todavía"
"fetchingAgenda" = "Obteniendo agendas"
"updatePreference" = "Preferencia de actualización"
"approved" = "Aprobado"
"voting" = "Votación"
"rejected" = "Rechazado"
"abandoned" = "Abandonado"
"inDiscussion" = "en discusión"
"fetchingProposals" = "Obtener propuestas..."
"underReview" = "Bajo revisión"
"noProposals" = "Sin propuestas %s"
"waitingForAuthor" = "Esperando a que el autor autorice la votación"
"waitingForAdmin" = "Esperando que el administrador active el inicio de la votación"
"voteTooltip" = "%d %% Sí se requieren votos para la aprobación"
"yes" = "Sí: "
"no" = "No: "
"totalVotes" = "Total de votos:  %6.0f"
"totalVotesReverse" = "%d Total de votos"
"quorumRequirement" = "Cuyo requerimiento:  %6.0f"
"discussions" = "Discusiones:   %d comentarios"
"published" = "Publicado:   %s"
"token" = "Simbólico:   %s"
"proposalVoteDetails" = "Detalles de la votación de la propuesta"
"votingServiceProvider" = "Proveedor de servicios de votación"
"selectVSP" = "Seleccione VSP..."
"addVSP" = "Agregar un nuevo VSP..."
"save" = "Guardar"
"noVSPLoaded" = "No se ha cargado vsp. Compruebe la conexión a Internet y vuelva a intentarlo."



`
