name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Libraries for gio
        run: |
          sudo apt update
          sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Cache (dependencies)
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-v2
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install linter
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1"

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Lint
        run: |
          export PATH=$PATH:~/go/bin
          golangci-lint run --deadline=10m \
            --disable-all --enable govet \
            --enable staticcheck --enable gosimple \
            --enable unconvert --enable ineffassign \
            --enable revive --enable goimports \
            --enable unparam

      - name: Test
        run: |
          env GORACE="halt_on_error=1" go test -race -short -count 1 ./...
