name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Libraries for gio
        run: |
          sudo apt update
          sudo apt install libwayland-dev libx11-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev

      - name: Cache (dependencies)
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install linter
        run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2"

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Lint
        run: |
          export PATH=$PATH:~/go/bin
          golangci-lint run --deadline=10m \
            --disable-all --enable govet \
            --enable staticcheck --enable gosimple \
            --enable unconvert --enable ineffassign \
            --enable structcheck --enable goimports \
            --enable misspell --enable unparam --enable go-lint
